spring:
  data:
    mongodb:
      uri: mongodb+srv://milenabertolini:N4UnTwICaVeYggsN@cluster0.ytnny.mongodb.net/
      database: myDatabase
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
